### ISSUE TITLE
libarmadito.h: No such file or directory

### ISSUE THREAD

**Issue by trasher** [armadito/deprecated-mod-h1#2]
Using latest source, i get the following:
```
module/moduleH1.c:22:25: fatal error: libarmadito.h: No such file or directory
```

Seems that libarmadito has been renamed armadito; the file previously in /usr/include/libarmadito/libarmadito.h no longer exists; /usr/include/libarmadito/armadito.h seems to replace it.

**Comment by vhamon** [comment]
Thanks for noticing it. It has been fixed in https://github.com/armadito/armadito-mod-h1/commit/bb34dfe054435f4d8a7795ee7a7a941bb7ac12f8. Build of this module is now okay.
